name: Addis Sport
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run package
      - uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ${{ matrix.os }}-build
          path: dist/*
